Repository elastic/go-sysinfo, pull requests merged in 2023-05, with the labels that each got.

#172 providers/darwin - kern.procargs2 guard against runtime panic
  .gitignore
  CHANGELOG.md
  providers/darwin/process_darwin.go
  providers/darwin/process_darwin_test.go
Labels: bug

#176 .github/workflows/release.yml - Fix checkout config
  .github/workflows/release.yml
Labels: skip-changelog

#177 .github/workfows/release.yml - Fix YAML multiline string format
  .github/workflows/release.yml
Labels: skip-changelog

#178 .github/workflows/release.yml - Pass GH_TOKEN to gh CLI
  .github/workflows/release.yml
Labels: skip-changelog

#175 Fix major and minor version parsing on older Windows
  .changelog/175.txt
  providers/windows/os_windows.go
  providers/windows/os_windows_test.go
Labels: bug

#182 system_test.go - Fix flaky TestProcesses
  system_test.go
Labels: skip-changelog

#184 providers/linux/capabilities_linux.go - Refresh capability names
  .changelog/184.txt
  providers/linux/capabilities_linux.go
Labels: enhancement
