Repository elastic/go-sysinfo, pull requests merged in 2023-08, with the labels that each got.

#188 AIX: Mappings for host memory info
  .changelog/188.txt
  providers/aix/host_aix_ppc64.go
Labels: enhancement

#189 ci: update badges
  README.md
Labels: skip-changelog

#186 linux: optimize parseKeyValue
  .changelog/186.txt
  providers/linux/capabilities_linux.go
  providers/linux/memory_linux.go
  providers/linux/process_linux.go
  providers/linux/seccomp_linux.go
  providers/linux/util.go
  providers/linux/util_test.go
  providers/linux/vmstat.go
Labels: enhancement, Team:Security-External Integrations
